name: 'psftp-action'
description: 'This action exposes the psftp command-line options to be executed from external file script. Very useful to automate SFTP deployments to any SFTP server.'
icon: 'upload-cloud'
color: 'blue'
inputs:
  host:  # id of input
    description: 'Remote SFTP Host'
    required: true
  user:  # id of input
    description: 'Session Username'
    required: true
  pass:  # id of input
    description: 'Session Password'
    required: true
  scriptPath:  # id of input
    description: 'Path to the file that contains the psftp commands to be executed'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
